Db homework. Serhii Liakh
Odin2345/cursor pull request #1
Opened 2019-09-30 14:32 UTC by Odin2345

2019-09-30 15:29 UTC, Odin2345 commented
![](https://github.trello.services/images/mini-trello-icon.png) [H/W #2. Serhii Liakh](https://trello.com/c/BpCWcbet/58-h-w-2-serhii-liakh)

2019-10-01 19:47 UTC, yuriimchg requested changes
привіт,
переглянув дз, код виглядає дуже добре :+1: 
нижче є одне зауваження щодо першого домашнього.

щодо другого, також все дуже добре працює
але в другому дз потрібно трохи виправити форматування (можна слідкувати за змінами за допомогою flake8 або pylint):
```
>>> flake8 homework.py
homework.py:21:30: W291 trailing whitespace
homework.py:22:80: E501 line too long (84 > 79 characters)
homework.py:38:17: W291 trailing whitespace
homework.py:54:17: W291 trailing whitespace
homework.py:55:23: W291 trailing whitespace
homework.py:72:25: W291 trailing whitespace
homework.py:73:39: W291 trailing whitespace
homework.py:88:30: W291 trailing whitespace
homework.py:89:25: W291 trailing whitespace
homework.py:90:35: W291 trailing whitespace
homework.py:107:23: W291 trailing whitespace
homework.py:124:23: W291 trailing whitespace
homework.py:125:23: W291 trailing whitespace
homework.py:152:80: E501 line too long (101 > 79 characters)
homework.py:160:42: W291 trailing whitespace
homework.py:161:23: W291 trailing whitespace
homework.py:162:25: W291 trailing whitespace
homework.py:163:38: W291 trailing whitespace
homework.py:175:17: W291 trailing whitespace
homework.py:176:23: W291 trailing whitespace
homework.py:192:17: W291 trailing whitespace
homework.py:193:23: W291 trailing whitespace
homework.py:210:23: W291 trailing whitespace
homework.py:226:27: W291 trailing whitespace
homework.py:227:22: W291 trailing whitespace
homework.py:228:29: W291 trailing whitespace
homework.py:229:54: W291 trailing whitespace
homework.py:246:22: W291 trailing whitespace
homework.py:247:29: W291 trailing whitespace
homework.py:248:54: W291 trailing whitespace
homework.py:263:59: W291 trailing whitespace
homework.py:264:23: W291 trailing whitespace
homework.py:265:26: W291 trailing whitespace
homework.py:281:80: E501 line too long (85 > 79 characters)
homework.py:281:86: W291 trailing whitespace
homework.py:282:63: W291 trailing whitespace
homework.py:283:23: W291 trailing whitespace
homework.py:284:28: W291 trailing whitespace
homework.py:285:49: W291 trailing whitespace

```
Також _на майбутнє_: для кожного дз потрібно створювати нову гілку в git для того, щоб легше було відслідковувати зміни. Кожна гілка після успішного пул реквесту мерджиться в `master` - тому й зручно використовувати один пул реквест на одне дз.

Наприклад, зараз: в мене є зауваження до дз №2, тому я не можу прийняти пул реквест, відповідно  дз #1 заблоковане другим.

2019-10-01 19:47 UTC, yuriimchg commented on git/homework.py
> +        print("Not valid input data")
цей рядок недосяжний для інтерпретатора, оскільки у 88 рядку підніметься ValueError

2019-10-01 19:47 UTC, yuriimchg commented on relational_database/homework.py
> +    #con.commit()
не потрібно залишати закоментований код  - він тільки захаращує модуль

2019-10-01 21:41 UTC, closed without merging

2019-10-04 12:17 UTC, dimigor commented on git/homework.py
> +    list.remove(7)
it is a bad implementation

2019-10-04 12:17 UTC, dimigor commented on git/homework.py
> +    return id(first) == id(second)
take a look at operator `is`