Homework Flask
Odin2345/cursor pull request #8
Opened 2019-10-23 15:14 UTC by Odin2345

2019-10-24 21:45 UTC, yuriimchg requested changes
привіт
перевірив дз, є зауваження:
* потрібно створити панель навігації. Ідеально, якщо на ній будуть робочі посилання на наявні ендпоінти + випадаючий список з ними (хоча достатньо створити щось одне)

2019-10-25 07:24 UTC, dimigor commented on flask/templates/fruits.html
> +        <li style="color:red;">{{fruit}}</li>
missed tab

2019-10-25 07:24 UTC, dimigor commented on flask/templates/fruits.html
> +        <li>{{fruit}}</li>
as above

2019-10-25 07:24 UTC, dimigor commented on flask/templates/fruits.html
> +{% endblock %}
endline

2019-10-25 07:24 UTC, dimigor commented on flask/templates/home.html
> +        <a href="/fruits" class="btn btn-primary">Fruits</a>
use url_for instead

2019-10-25 07:24 UTC, dimigor commented on flask/templates/vegetables.html
> +<div class="d-flex flex-row justify-content-center align-items-center" style="height: 300px;">
itis bad to define a style in Html

2019-10-25 12:14 UTC, Odin2345 commented on flask/templates/fruits.html
> +        <li style="color:red;">{{fruit}}</li>
fixed

2019-10-25 12:14 UTC, Odin2345 commented on flask/templates/fruits.html
> +        <li>{{fruit}}</li>
fixed

2019-10-25 12:14 UTC, Odin2345 commented on flask/templates/fruits.html
> +{% endblock %}
fixed

2019-10-25 12:14 UTC, Odin2345 commented on flask/templates/vegetables.html
> +<div class="d-flex flex-row justify-content-center align-items-center" style="height: 300px;">
fixed

2019-10-25 12:14 UTC, Odin2345 commented on flask/templates/home.html
> +        <a href="/fruits" class="btn btn-primary">Fruits</a>
fixed

2019-10-25 12:31 UTC, dimigor approved these changes

2019-10-25 12:33 UTC, merged